name: Playlist Workflow

on:
   workflow_dispatch:

jobs:
    create-playlist:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up uv
              uses: astral-sh/setup-uv@v6
              with:
                version: "0.8.15"
                
            - name: Set up python environment
              working-directory: src
              run: uv sync